const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.jpg",
    description: "Airpod prod",
    brand: "Apple",
    category: "Electronics",
    price: 99.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/camera.jpg",
    description: "Airpod prod",
    brand: "Apple",
    category: "Electronics",
    price: 99.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/mouse.jpg",
    description: "Airpod prod",
    brand: "Apple",
    category: "Electronics",
    price: 99.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/alexa.jpg",
    description: "Airpod prod",
    brand: "Apple",
    category: "Electronics",
    price: 99.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/playstation.jpg",
    description: "Airpod prod",
    brand: "Apple",
    category: "Electronics",
    price: 99.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
